version: "3.4"
volumes:
  postgis_data:
services:
  postgis-db:
    image: "postgis/postgis"
    ports:
      - "5432:5432"
    env_file:
      - packages/scripts/.env
    volumes:
      - ${POSTGIS_DATA:-postgis_data}:/var/lib/postgresql/db
  pgadmin:
    image: "dpage/pgadmin4"
    ports:
      - "5050:80"
    env_file:
      - packages/scripts/.env
    depends_on:
      - postgis-db
